In [ ]:
import pandas as pd
import numpy as np


from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors


master_df=pd.read_csv(r"C:\Users\HEMANATH\Desktop\FIFA\data\processed\clustered_players.csv")
master_df
print(master_df.columns.tolist())

['player_id', 'first_name', 'last_name', 'name', 'last_season', 'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth', 'country_of_citizenship', 'date_of_birth', 'sub_position', 'position', 'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name', 'image_url', 'international_caps', 'international_goals', 'current_national_team_id', 'url', 'current_club_domestic_competition_id', 'current_club_name', 'market_value_in_eur', 'highest_market_value_in_eur', 'matches', 'goals', 'assists', 'yellow_cards', 'red_cards', 'minutes_played', 'data_of_birth', 'age', 'goal_per90', 'assists_per90', 'goals_per90', 'card_per90', 'cards_per90', 'log_market_value', 'intl_goal_ratio', 'position_group', 'goal_contribution_per90', 'cluster', 'cluster_name', 'PC1', 'PC2']

In [14]:
features = [
    "goals_per90",
    "assists_per90",
    "cards_per90",
    "age",
    "log_market_value"
]

In [15]:
X=master_df[features].fillna(0)
X

       goals_per90  assists_per90  cards_per90  age  log_market_value
0         0.490463       0.255450     0.194142   48         13.815512
1         0.000000       0.000000     0.039976   45         13.527830
2         0.389167       0.133136     0.122895   45         13.815512
3         0.000000       0.000000     0.000000   45         11.512935
4         0.025112       0.050223     0.100446   48         12.899222
...            ...            ...          ...  ...               ...
17462     0.629371       0.125874     0.062937   22          0.000000
17463     0.317700       0.408472     0.226929   19          0.000000
17464     0.332278       0.237342     0.047468   19          0.000000
17465     0.398010       0.273632     0.099502   19         17.622173
17466     0.197224       0.000000     0.328707   19         13.815512

[17467 rows x 5 columns]

In [16]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_scaled

array([[ 2.71434955,  1.94277315, -0.08593438,  2.33436393,  0.35168459],
       [-0.85165762, -1.04598053, -1.39688761,  1.88218161,  0.2516541 ],
       [ 1.97785626,  0.51170837, -0.69178549,  1.88218161,  0.35168459],
       ...,
       [ 1.564237  ,  1.73091213, -1.33317862, -2.03673182, -4.45213958],
       [ 2.0421503 ,  2.15550501, -0.8907037 , -2.03673182,  1.67530786],
       [ 0.58229924, -1.04598053,  1.05834938, -2.03673182,  0.35168459]],
      shape=(17467, 5))

In [17]:
nn=NearestNeighbors(n_neighbors=6,metric="euclidean")
nn.fit(X_scaled)

NearestNeighbors(metric='euclidean', n_neighbors=6)

In [18]:
def recommend_player(player_name):

    matches = master_df[
        master_df["name"]
        .str.lower()
        .str.contains(
            player_name.lower(),
            na=False
        )
    ]

    if len(matches) == 0:
        return "Player not found"

    idx = matches.index[0]

    distances, indices = nn.kneighbors(
        [X_scaled[idx]]
    )

    recommendations = (
        master_df.iloc[indices[0]]
        [
            [
                "name",
                "position_group",
                "age",
                "market_value_in_eur",
                "cluster_name"
            ]
        ]
    )

    return recommendations

In [22]:
recommend_player("Haaland")

,name,position_group,age,market_value_in_eur,cluster_name
13099,Erling Haaland,Attack,25,200000000.0,Elite Attacks
11389,Viktor Gyökeres,Attack,28,70000000.0,Elite Attacks
15800,Marcos Leonardo,Attack,23,20000000.0,Elite Attacks
11771,Kylian Mbappé,Attack,27,180000000.0,Experienced Professionals
6936,Harry Kane,Attack,32,65000000.0,Experienced Professionals
16987,Franculino,Attack,21,22000000.0,Elite Attacks